{{- range $key, $value := .Values.hosts }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $value.name}}-configs"
data:
  nginx.conf: |
    server {
      listen 80;

      location / {
      return 200 {{ $value.name }};
        }
    }
---
{{- end }}
