{{- $fullName := include "test-multiple-ingresses.fullname" . -}}
{{- range $key, $value := .Values.hosts }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $value.name }}-{{ $fullName }}"
  labels:
    host: "{{ $value.name }}"
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      host: "{{ $value.name }}"
  template:
    metadata:
      labels:
        host: "{{ $value.name }}"
    spec:
      containers:
        - name: "{{ $value.name }}"
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: config
          configMap:
            name: "{{ $value.name}}-configs"
---
{{- end }}
