apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-multiple-ingresses.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
