{{- $fullName := include "test-multiple-ingresses.fullname" . -}}
{{- range $key, $value := .Values.hosts }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ $value.name }}-{{ $fullName }}"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    host: "{{ $value.name }}"
---
{{- end }}
